<?xml version="1.0" encoding="UTF-8" ?>
<testsuites disabled="0" errors="0" failures="1" tests="2" time="7.537">
 <testsuite name="Calculator" timestamp="2021-01-20T20:07:52" hostname="localhost" time="7.537" errors="0" tests="2" skipped="0" disabled="0" failures="1">
  <testcase classname="Calculator" name="Addition" time="4.363" />
  <testcase classname="Calculator" name="Substraction" time="3.159">
   <failure type="toEqual" message="Expected &apos;4&apos; to equal &apos;5&apos;."><![CDATA[Error: Failed expectation
    at CalculatorPage.verifyOutput (C:\Protractor_Automation\Tests\CalculatorPage.js:22:38)
    at UserContext.<anonymous> (C:\Protractor_Automation\Tests\Calculator.js:24:24)
    at C:\Users\User\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\User\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\User\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\User\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\User\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\User\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at C:\Users\User\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2974:25]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>